from __future__ import annotations

from enum import StrEnum


class BaselineStatus(StrEnum):
    PROPOSED = "PROPOSED"
    ACTIVE = "ACTIVE"
    REJECTED = "REJECTED"
    FAILED_AT_BASE = "FAILED_AT_BASE"
    SUPERSEDED = "SUPERSEDED"
    RETIRED = "RETIRED"
    REVALIDATION_REQUIRED = "REVALIDATION_REQUIRED"


class BaselineSource(StrEnum):
    BROWNFIELD_EXISTING_TEST = "BROWNFIELD_EXISTING_TEST"
    BROWNFIELD_CHARACTERIZATION = "BROWNFIELD_CHARACTERIZATION"
    BROWNFIELD_RUNTIME_PROBE = "BROWNFIELD_RUNTIME_PROBE"
    RELEASE_PROMOTION = "RELEASE_PROMOTION"
    CHANGE = "CHANGE"
    REPAIR = "REPAIR"


class BaselineCheckKind(StrEnum):
    EXISTING_TEST = "EXISTING_TEST"
    AUTHORED_TEST = "AUTHORED_TEST"
    API_PROBE = "API_PROBE"


class BaselineActivation(StrEnum):
    HUMAN = "HUMAN"
    AUTO_DETERMINISTIC = "AUTO_DETERMINISTIC"


class PromotionDecisionType(StrEnum):
    PROMOTE_AS_CANONICAL = "PROMOTE_AS_CANONICAL"
    CONFIRM_EXISTING = "CONFIRM_EXISTING"
    REJECT_AS_NOT_INTENDED = "REJECT_AS_NOT_INTENDED"
    DEFER = "DEFER"
    APPROVE_AS_PROJECT_ARCHITECTURE = "APPROVE_AS_PROJECT_ARCHITECTURE"
    ACTIVATE = "ACTIVATE"
    RESOLVE = "RESOLVE"
    ACCEPT_KNOWN_GAP = "ACCEPT_KNOWN_GAP"


class ReadinessResult(StrEnum):
    READY = "READY"
    NOT_READY = "NOT_READY"
