"""Phase 01 — actors, projects, repositories, workspaces

Revision ID: 0001_p01_repos
Revises: 0000_p00_baseline
Create Date: 2026-10-01 22:31:30.947777

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001_p01_repos"
down_revision: str | None = "0000_p00_baseline"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "actors",
        sa.Column(
            "kind",
            sa.Enum("HUMAN", "AGENT", "SYSTEM", "INTEGRATION", name="actorkind"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("roles", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_actors")),
        sa.UniqueConstraint("name", name=op.f("uq_actors_name")),
    )
    op.create_table(
        "projects",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("description", sa.String(length=4096), nullable=True),
        sa.Column(
            "readiness_state",
            sa.Enum("UNKNOWN", "ONBOARDING", "READY_FOR_CHANGE", name="projectreadiness"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
        sa.UniqueConstraint("key", name=op.f("uq_projects_key")),
    )
    op.create_table(
        "api_tokens",
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["actors.id"], name=op.f("fk_api_tokens_actor_id_actors")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_api_tokens_token_hash")),
    )
    op.create_index(op.f("ix_api_tokens_actor_id"), "api_tokens", ["actor_id"], unique=False)
    op.create_table(
        "project_sequences",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("sequence_name", sa.String(length=64), nullable=False),
        sa.Column("next_value", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_project_sequences_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("project_id", "sequence_name", name=op.f("pk_project_sequences")),
        sa.UniqueConstraint(
            "project_id", "sequence_name", name=op.f("uq_project_sequences_project_id")
        ),
    )
    op.create_table(
        "repositories",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum("GREENFIELD_MANAGED", "EXTERNAL_CLONE", name="repositorysourcetype"),
            nullable=False,
        ),
        sa.Column(
            "provider",
            sa.Enum("LOCAL", "GITHUB", "GITEA", "GITLAB", "BITBUCKET", name="repositoryprovider"),
            nullable=False,
        ),
        sa.Column("remote_url", sa.String(length=2048), nullable=True),
        sa.Column("default_branch", sa.String(length=256), nullable=False),
        sa.Column("registered_sha", sa.String(length=64), nullable=True),
        sa.Column("canonical_commit", sa.String(length=64), nullable=True),
        sa.Column("released_commit", sa.String(length=64), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PROVISIONING", "CLONING", "READY", "SYNCING", "ERROR", name="repositorystatus"
            ),
            nullable=False,
        ),
        sa.Column("status_reason", sa.String(length=1024), nullable=True),
        sa.Column("workspace_id", sa.Uuid(), nullable=True),
        sa.Column("credential_ref", sa.String(length=512), nullable=False),
        sa.Column("state_version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "credential_ref ~ '^(none|env|file|secret):[A-Za-z0-9_./-]*$'",
            name=op.f("ck_repositories_ck_repositories_credential_ref"),
        ),
        sa.CheckConstraint(
            "remote_url IS NULL OR remote_url !~ '^[a-z+]+://[^/@]*@'",
            name=op.f("ck_repositories_ck_repositories_remote_url_no_userinfo"),
        ),
        sa.CheckConstraint(
            "status <> 'READY' OR canonical_commit IS NOT NULL",
            name=op.f("ck_repositories_ck_repositories_ready_has_commit"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_repositories_project_id_projects")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["repository_workspaces.id"],
            name="fk_repositories_workspace_id",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repositories")),
        sa.UniqueConstraint("project_id", name=op.f("uq_repositories_project_id")),
    )
    op.create_table(
        "repository_workspaces",
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_type", sa.String(length=32), nullable=False),
        sa.Column("storage_backend", sa.String(length=64), nullable=False),
        sa.Column("logical_location", sa.String(length=512), nullable=False),
        sa.Column("materialized_commit", sa.String(length=64), nullable=True),
        sa.Column(
            "state",
            sa.Enum(
                "PENDING",
                "MATERIALIZING",
                "READY",
                "REFRESHING",
                "MISSING",
                "ERROR",
                name="workspacestate",
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "logical_location !~ '(^/|^[A-Za-z]:|\\.\\.)'",
            name=op.f("ck_repository_workspaces_ck_repository_workspaces_logical"),
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
            name=op.f("fk_repository_workspaces_repository_id_repositories"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repository_workspaces")),
        sa.UniqueConstraint(
            "repository_id", "workspace_type", name=op.f("uq_repository_workspaces_repository_id")
        ),
        sa.UniqueConstraint(
            "storage_backend",
            "logical_location",
            name=op.f("uq_repository_workspaces_storage_backend"),
        ),
    )
    op.create_index(
        op.f("ix_repository_workspaces_repository_id"),
        "repository_workspaces",
        ["repository_id"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index(
        op.f("ix_repository_workspaces_repository_id"), table_name="repository_workspaces"
    )
    op.drop_table("repository_workspaces")
    op.drop_table("repositories")
    op.drop_table("project_sequences")
    op.drop_index(op.f("ix_api_tokens_actor_id"), table_name="api_tokens")
    op.drop_table("api_tokens")
    op.drop_table("projects")
    op.drop_table("actors")
    for enum_name in (
        "repositorystatus",
        "repositoryprovider",
        "repositorysourcetype",
        "projectreadiness",
        "actorkind",
        "workspacestate",
    ):
        op.execute(f'DROP TYPE IF EXISTS "{enum_name}" CASCADE')
