export const qk = {
  projects: () => ["projects"] as const,
  project: (id: string) => ["project", id] as const,
  cycles: (projectId: string) => ["cycles", projectId] as const,
  cycle: (id: string) => ["cycle", id] as const,
  cycleTasks: (cycleId: string) => ["cycleTasks", cycleId] as const,
  taskDag: (cycleId: string) => ["taskDag", cycleId] as const,
  task: (id: string) => ["task", id] as const,
  execution: (id: string) => ["execution", id] as const,
  cycleExecutions: (cycleId: string) => ["cycleExecutions", cycleId] as const,
  approvals: () => ["approvals"] as const,
  inbox: () => ["inbox"] as const,
  releaseEligibility: (cycleId: string) => ["releaseEligibility", cycleId] as const,
  releases: (projectId: string) => ["releases", projectId] as const,
  release: (id: string) => ["release", id] as const,
  actor: () => ["actor"] as const,
  cycleEvents: (cycleId: string) => ["cycleEvents", cycleId] as const,
  gates: (icId: string) => ["gates", icId] as const,
  findings: (cycleId: string) => ["findings", cycleId] as const,
  ics: (cycleId: string) => ["ics", cycleId] as const,
  controlPlane: (cycleId: string) => ["controlPlane", cycleId] as const,
  cycleOverview: (cycleId: string) => ["cycleOverview", cycleId] as const,
  projectEvents: (projectId: string) => ["projectEvents", projectId] as const,
  actions: (projectId: string, cycleId?: string) =>
    ["actions", projectId, cycleId ?? "all"] as const,
  impact: (cycleId: string) => ["impact", cycleId] as const,
  codeSearch: (repoId: string, q: string) => ["codeSearch", repoId, q] as const,
  repository: (repoId: string) => ["repository", repoId] as const,
  repositoryForProject: (projectId: string) => ["repositoryForProject", projectId] as const,
  repoWorkspace: (repoId: string) => ["repoWorkspace", repoId] as const,
  repoRevisions: (repoId: string) => ["repoRevisions", repoId] as const,
  repoMaterializations: (repoId: string) => ["repoMaterializations", repoId] as const,
  executionWorkspaces: (repoId: string, cycleId?: string) =>
    ["executionWorkspaces", repoId, cycleId ?? "all"] as const,
  commitLedger: (repoId: string) => ["commitLedger", repoId] as const,
  codeEntities: (indexVersionId: string, filters?: string) =>
    ["codeEntities", indexVersionId, filters ?? ""] as const,
  entityNeighbors: (entityId: string, depth: number) =>
    ["entityNeighbors", entityId, depth] as const,
  evidence: (key: string) => ["evidence", key] as const,
  obligations: (icId: string) => ["obligations", icId] as const,
  releaseManifest: (releaseId: string) => ["releaseManifest", releaseId] as const,
  controlExplain: (type: string, id: string) => ["controlExplain", type, id] as const,
  scenarioPosition: () => ["scenarioPosition"] as const,
};
