from __future__ import annotations

from enum import StrEnum


class ActorKind(StrEnum):
    HUMAN = "HUMAN"
    AGENT = "AGENT"
    SYSTEM = "SYSTEM"
    INTEGRATION = "INTEGRATION"


class ActorRole(StrEnum):
    OPERATOR = "OPERATOR"
    APPROVER = "APPROVER"
    VIEWER = "VIEWER"
    SYSTEM = "SYSTEM"
    INTEGRATION = "INTEGRATION"


class DeliveryCycleType(StrEnum):
    GREENFIELD_BUILD = "GREENFIELD_BUILD"
    BROWNFIELD_ONBOARDING = "BROWNFIELD_ONBOARDING"
    FEATURE_CHANGE = "FEATURE_CHANGE"
    BUG_FIX = "BUG_FIX"
    REMEDIATION = "REMEDIATION"


class ProjectReadiness(StrEnum):
    UNKNOWN = "UNKNOWN"
    ONBOARDING = "ONBOARDING"
    READY_FOR_CHANGE = "READY_FOR_CHANGE"


class WorkType(StrEnum):
    ANALYSIS = "ANALYSIS"
    CODE_CHANGE = "CODE_CHANGE"
    VERIFICATION = "VERIFICATION"
    INTEGRATION = "INTEGRATION"
    RELEASE = "RELEASE"


class TaskOrigin(StrEnum):
    IMPLEMENTATION_PLAN = "IMPLEMENTATION_PLAN"
    REMEDIATION = "REMEDIATION"
    REPAIR = "REPAIR"
    CONTROL_PLANE = "CONTROL_PLANE"


class TaskStatus(StrEnum):
    DRAFT = "DRAFT"
    BLOCKED = "BLOCKED"
    READY = "READY"
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    STALE = "STALE"
    REVALIDATION_REQUIRED = "REVALIDATION_REQUIRED"


class TaskContractStatus(StrEnum):
    DRAFT = "DRAFT"
    ISSUED = "ISSUED"
    SUPERSEDED = "SUPERSEDED"


class ApprovalType(StrEnum):
    SCOPE = "SCOPE"
    ARCHITECTURE = "ARCHITECTURE"
    ARCHITECTURE_DELTA = "ARCHITECTURE_DELTA"
    IMPLEMENTATION_SPEC = "IMPLEMENTATION_SPEC"
    SPEC_DELTA = "SPEC_DELTA"
    SPEC_DECISION = "SPEC_DECISION"
    REPAIR_SPEC = "REPAIR_SPEC"
    UNREPRODUCED_REPAIR = "UNREPRODUCED_REPAIR"
    EXPECTED_BEHAVIOR = "EXPECTED_BEHAVIOR"
    TASK_PLAN = "TASK_PLAN"
    PROMOTION = "PROMOTION"
    FINDING_WAIVER = "FINDING_WAIVER"
    ACTION = "ACTION"
    RELEASE = "RELEASE"
    DEPLOYMENT = "DEPLOYMENT"
    READINESS = "READINESS"


class ApprovalStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"


class RepositorySourceType(StrEnum):
    GREENFIELD_MANAGED = "GREENFIELD_MANAGED"
    EXTERNAL_CLONE = "EXTERNAL_CLONE"


class RepositoryProvider(StrEnum):
    LOCAL = "LOCAL"
    GITHUB = "GITHUB"
    GITEA = "GITEA"
    GITLAB = "GITLAB"
    BITBUCKET = "BITBUCKET"


class RepositoryStatus(StrEnum):
    PROVISIONING = "PROVISIONING"
    CLONING = "CLONING"
    READY = "READY"
    SYNCING = "SYNCING"
    ERROR = "ERROR"


class WorkspaceState(StrEnum):
    PENDING = "PENDING"
    MATERIALIZING = "MATERIALIZING"
    READY = "READY"
    REFRESHING = "REFRESHING"
    MISSING = "MISSING"
    ERROR = "ERROR"


class RevisionCause(StrEnum):
    MATERIALIZED = "MATERIALIZED"
    INTEGRATION_READY = "INTEGRATION_READY"
    RELEASED = "RELEASED"
    EXTERNAL_SYNC = "EXTERNAL_SYNC"
    REVERTED = "REVERTED"


class CommandLogStatus(StrEnum):
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"


class ExecutionStatus(StrEnum):
    QUEUED = "QUEUED"
    LEASED = "LEASED"
    STARTED = "STARTED"
    CHECKPOINTED = "CHECKPOINTED"
    OUTPUT_PRODUCED = "OUTPUT_PRODUCED"
    VALIDATING = "VALIDATING"
    COMMITTED = "COMMITTED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    TIMED_OUT = "TIMED_OUT"
    CANCELLED = "CANCELLED"
    STALE = "STALE"


class LeaseState(StrEnum):
    ACTIVE = "ACTIVE"
    RELEASED = "RELEASED"
    EXPIRED = "EXPIRED"


class CheckpointReason(StrEnum):
    CLARIFICATION = "CLARIFICATION"
    APPROVAL = "APPROVAL"
    EXTERNAL_DEPENDENCY = "EXTERNAL_DEPENDENCY"
    RECONCILIATION = "RECONCILIATION"
    WAITING_EXTERNAL = "WAITING_EXTERNAL"


class CheckpointResolution(StrEnum):
    RESUME_SAME = "RESUME_SAME"
    NEW_EXECUTION = "NEW_EXECUTION"
    CANCELLED = "CANCELLED"


class ClarificationStatus(StrEnum):
    OPEN = "OPEN"
    ANSWERED = "ANSWERED"
    CANCELLED = "CANCELLED"


class ActionStatus(StrEnum):
    REQUESTED = "REQUESTED"
    DENIED = "DENIED"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    EXECUTING = "EXECUTING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    RECONCILIATION_REQUIRED = "RECONCILIATION_REQUIRED"


class ExecutionWorkspaceType(StrEnum):
    GIT_WORKTREE = "GIT_WORKTREE"


class ExecutionWorkspaceMode(StrEnum):
    WRITABLE = "WRITABLE"
    READONLY = "READONLY"


class ExecutionWorkspaceState(StrEnum):
    CREATING = "CREATING"
    ACTIVE = "ACTIVE"
    RETAINED = "RETAINED"
    REMOVED = "REMOVED"
    ORPHANED = "ORPHANED"


class MaterializationKind(StrEnum):
    PROVISION = "PROVISION"
    CLONE = "CLONE"
    FETCH = "FETCH"


class MaterializationAttemptStatus(StrEnum):
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"


class ConnectorActionStatus(StrEnum):
    PENDING = "PENDING"
    SUCCEEDED = "SUCCEEDED"
    FAILED_RETRYABLE = "FAILED_RETRYABLE"
    FAILED_FINAL = "FAILED_FINAL"
    UNKNOWN = "UNKNOWN"


class SpecStatus(StrEnum):
    DRAFT = "DRAFT"
    PROPOSED = "PROPOSED"
    APPROVED = "APPROVED"
    SUPERSEDED = "SUPERSEDED"
    REJECTED = "REJECTED"
    PROMOTED = "PROMOTED"
    CONFIRMED_EXISTING = "CONFIRMED_EXISTING"


class SpecKind(StrEnum):
    CANONICAL = "CANONICAL"
    RECOVERED = "RECOVERED"


class ModelOrigin(StrEnum):
    GREENFIELD = "GREENFIELD"
    RECOVERED = "RECOVERED"
    HUMAN = "HUMAN"
    CHANGE = "CHANGE"
    REPAIR = "REPAIR"


class EvidenceRequirement(StrEnum):
    EXECUTABLE = "EXECUTABLE"
    RUNTIME = "RUNTIME"
    EXECUTABLE_OR_RUNTIME = "EXECUTABLE_OR_RUNTIME"
    REVIEW_ALLOWED = "REVIEW_ALLOWED"


class KnowledgeClass(StrEnum):
    FACT = "FACT"
    INFERENCE = "INFERENCE"
    UNCERTAINTY = "UNCERTAINTY"
    DECISION = "DECISION"
    ASSUMPTION = "ASSUMPTION"


class EntityStatus(StrEnum):
    PROPOSED = "PROPOSED"
    APPROVED = "APPROVED"
    RETIRED = "RETIRED"


class InboundEventStatus(StrEnum):
    RECEIVED = "RECEIVED"
    DUPLICATE = "DUPLICATE"
    REJECTED = "REJECTED"
    ACCEPTED = "ACCEPTED"
    STALE = "STALE"


class IntegrationAuthKind(StrEnum):
    BEARER = "BEARER"
    HMAC_SHA256 = "HMAC_SHA256"
    NONE_LOCAL = "NONE_LOCAL"


class DecompositionStatus(StrEnum):
    PROPOSED = "PROPOSED"
    SUPERSEDED = "SUPERSEDED"
    ACCEPTED = "ACCEPTED"


class KnowledgeItemStatus(StrEnum):
    ACTIVE = "ACTIVE"
    SUPERSEDED = "SUPERSEDED"
    REJECTED = "REJECTED"
